### ISSUE TITLE
undefined method `to_a' for Sprockets::Asset - Perfectly working teaspoon spec is not working with 4.0

### ISSUE THREAD

**Issue by thebravoman** [rails/sprockets#650]
### Expected behavior
Running a jasmine spec with teaspoon as I've done for this specs for the last two years.

### Actual behavior
When running the specs with Sprockets 4
````
ActionView::Template::Error (undefined method `to_a' for #<Sprockets::Asset:0x00007f59b022fb58>
Did you mean?  to_s):
    1: <%= javascript_include_tag *@suite.spec_assets, debug: @suite.config.expand_assets, allow_non_precompiled: true %>
    2: <script type="text/javascript">
    3:   Teaspoon.onWindowLoad(Teaspoon.execute);
    4: </script>
````

### System configuration

- 4.0.0
- 2.6.5

### Example App (Reproduction) - THIS IS IMPORTANT YOUR ISSUE LIKELY WILL NOT BE RESOLVED WITHOUT THIS

Should I even try to provide an example app or it is expected that Sprocktes::Asset will not have a to_a method?
