### ISSUE TITLE
Rails.application no longer available in sprockets assets

### ISSUE THREAD

**Issue by vincentwoo** [rails/sprockets#394]
### Expected behavior

I have an existing `foo.coffee.erb` file that does this in sprockets 3:

```coffee
constants = {
  SOME_VAR:       '<%= Rails.application.secrets.some_var %>'
}
```

### Actual behavior

On master sprockets, I get: `undefined method 'application' for Sprockets::Rails:Module`. This is after many attempts to diagnose an even more cryptic `NoMethodError - undefined method 'env' for Sprockets::Rails:Module:`. I did not get the "real" error message until I deleted all my javascript and started adding it back line by line.

### System configuration

- Sprockets version: master
- Ruby version: 2.3.1

### Example App

n/a atm

**Comment by schneems** [comment]
Thats weird that it would expect that to be under the `Sprockets` namespace. Try using `::Rails.application.secrets.some_var` instead. Also doing that is not going to end well, unless you also add that variable to your sprockets cache key, otherwise if you change it your assets won't get updated.

**Comment by vincentwoo** [comment]
What is the recommended path for getting `secrets.yml` data into precompiled assets?

**Comment by vincentwoo** [comment]
Also, this is probably a big thing that should be added to the upgrade readme, imo. Tons of asset erb code out there that has stuff like

```
<% if Rails.env.development? %>
```

**Comment by schneems** [comment]
You need to do something like 

```
depend_on ../config/secrets.yml
```

Then when the file changes, sprockets knows so your assets re-compile. This isn't a change with Sprockets 4, this is how all versions of sprockets work (regarding the cache)

**Comment by vincentwoo** [comment]
Oh, we do that already, but it doesn't work in sprockets 3 either, because Rails doesn't reload the actual in-memory variable when you change the yml file, so it almost doesn't even matter.

The question was, more specifically, how do you *get* the data from secrets.yml *into* a precompiled file. Rails loads secrets.html into Rails.application.secrets.

**Comment by schneems** [comment]
You would do it like you did, but make sure you've got the depend on declaration and you're good to go.

**Comment by matthewd** [comment]
> I did not get the "real" error message until I deleted all my javascript and started adding it back line by line

Ughh... do we not produce a useful backtrace for erb files? I thought we did. 😕 

---

> undefined method 'application' for Sprockets::Rails:Module

@bouk I suspect we broke this in #365

**Comment by bouk** [comment]
Yeah, it seems the change to use `engine.result(context.instance_eval('binding'))` made it so that `Rails` is now resolved to `Sprockets::Rails`. I'll get a PR up to fix this

**Comment by bouk** [comment]
I don't have any ideas on how to fix this actually... It seems unlikely that there's a way to define and enable access to the `ENV` constant on the class, while resolving any other constants that are also in the context of that class the the top-level variant. Any ideas @matthewd @schneems?

**Comment by schneems** [comment]
It definitely broke in #365 . I'm toying with it right now, but i'm at somewhat of a loss currently. Going to revert, and add a test for accessing top level constants. Hopefully we can figure something out

**Comment by schneems** [comment]
I tried writing a failing test, but this passes even with the ENV patch

```ruby
  def test_compile_js_erb_template_with_top_level_constant_access
    environment = Sprockets::Environment.new
    require 'sass'

    input = {
      environment: environment,
      filename: "foo.js.erb",
      content_type: 'application/javascript',
      data: "var sass_version = '<%= Sass::VERSION %>';",
      metadata: {},
      cache: Sprockets::Cache.new
    }

    assert_match /sass_version/, Sprockets::ERBProcessor.call(input)[:data]
  end
```

**Comment by bouk** [comment]
For that to fail, there would have to be a Sprockets::Sass constant that doesn't have the VERSION constant

**Comment by schneems** [comment]
Interesting, didn't realize that was the failure mode. Thanks.
